name: CI/CD

on: [push, pull_request]

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build .xpi package
        run: npx web-ext build
      - name: List files inside TabSearch.xpi
        run: unzip -l web-ext-artifacts/tab_search-*.xpi
      - uses: actions/upload-artifact@v7
        with:
          name: tab_search.xpi
          path: web-ext-artifacts/tab_search-*.xpi